version: "3.1"

services:
    mysql:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: mypack
        # So you don't have to use root, but you can if you like
        MYSQL_USER: user
        # You can use whatever password you like
        MYSQL_PASSWORD: 123
        # Password for root access
        MYSQL_ROOT_PASSWORD: 123
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - 3308:3306
      volumes:
        - myPack:/var/lib/mysql

    dockerPhpMyadmin:
      image: phpmyadmin
      environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
      links:
        - mysql
      restart: always
      ports:
        - 8081:80

    dockerJboss:
      image: quay.io/wildfly/wildfly
      ports:
        - 8085:8080
      volumes:
        - ./target/mypack-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war


# Names our volume
volumes:
  myPack: {}
